import {
  Wind, Refrigerator, Droplets, Droplet, Fan, Lightbulb, Tv, Laptop, Smartphone, Waves, Shirt,
  CookingPot, WashingMachine, Snowflake, Wifi, Package, Thermometer, Power, Zap, Plug,
  BatteryCharging, Moon, Sun, Percent, Calendar, Microwave, CupSoda, Sandwich, Blend, ChefHat,
  Coffee, Flame, Speaker, Gamepad2, DoorOpen, Router, Camera,
  type LucideIcon,
} from 'lucide-react'

export const ICONS: Record<string, LucideIcon> = {
  wind: Wind,
  refrigerator: Refrigerator,
  droplets: Droplets,
  droplet: Droplet,
  fan: Fan,
  lightbulb: Lightbulb,
  tv: Tv,
  laptop: Laptop,
  smartphone: Smartphone,
  waves: Waves,
  shirt: Shirt,
  'cooking-pot': CookingPot,
  'washing-machine': WashingMachine,
  snowflake: Snowflake,
  wifi: Wifi,
  package: Package,
  thermometer: Thermometer,
  power: Power,
  zap: Zap,
  plug: Plug,
  'battery-charging': BatteryCharging,
  moon: Moon,
  sun: Sun,
  percent: Percent,
  calendar: Calendar,
  microwave: Microwave,
  'cup-soda': CupSoda,
  sandwich: Sandwich,
  blend: Blend,
  'chef-hat': ChefHat,
  coffee: Coffee,
  flame: Flame,
  speaker: Speaker,
  'gamepad-2': Gamepad2,
  'door-open': DoorOpen,
  router: Router,
  camera: Camera,
}

export function iconFor(id: string): LucideIcon {
  return ICONS[id] ?? Package
}
